### ISSUE TITLE
Question: How can I play wip wurst versions?

### ISSUE THREAD

**Issue by Grievus** [Wurst-Imperium/Wurst-Client#2179] opened 2015-09-09 18:43 UTC
Or isn't this possible?

**Comment by pokeball99** [comment] 2015-09-09 19:30
your talking about build versions? dupe of #1885

**Comment by Alexander01998** [comment] 2015-09-09 20:25
A tutorial for that can be found here: https://www.wurst-client.tk/wiki/Tutorials/How-to-Debug-Wurst-In-Eclipse/

Note that it requires experience with Eclipse, Git and the MCP.

**Closed by Alexander01998** 2015-09-09 20:25 UTC
