### ISSUE TITLE
Remove all friends

### ISSUE THREAD

**Issue by ekyl** [Wurst-Imperium/Wurst-Client#922] opened 2015-06-11 08:01 UTC
I'd like to see a feature that lets you remove all of your friends. I think this would be very easy to implement...

**Comment by OMGchangeMYusername** [comment] 2015-06-11 09:06
First Duplicate Of #1 Ever!
I think this guy needs reward xD

**Comment by GummiBoat** [comment] 2015-06-11 09:21
@OMGchangeMYusername :trophy: <- is this enough?

Please search for your matter the next time, before you open a new issue.
![](http://puu.sh/ikCE3/96754c0e34.png)

**Closed** 2015-06-11 14:04 UTC
Labels: duplicate
