### ISSUE TITLE
WurstChat

### ISSUE THREAD

**Issue by solidshadow96** [Wurst-Imperium/Wurst-Client#2060] opened 2015-08-30 19:18 UTC
If there is a way to have a type of code written in chat that only the wurst client can decipher so people with the wurst client could have conversions that only users understand for example
$w(Talking in wurst chat so all wurst clients know that the upcoming sentence need to be deciphered)
26=A so each letter of the alphabet it backwards to 26 so b is 25 and c is 24 and so on.
this would be cool and useful because sometimes your not sure if someone is hacking and this would be a good way of knowing

**Comment by TheIonosphere** [comment] 2015-08-30 22:38
Except that within a few weeks, it would become widely known that this functionality is offered by the Wurst client. Even if they cannot understand the content of the message it would be immediately evident who is hacking. This applies to all types of message encryption.

**Comment by pokeball99** [comment] 2015-08-31 03:06
^

**Comment by solidshadow96** [comment] 2015-08-31 03:45
Very true
Or what about if the hack is on you could type you type $w(your message) and all letters after the $w would be different so lets just say all a's would then become z's so noone would understand almost as if it were a different language still using the alphabet?

**Comment by solidshadow96** [comment] 2015-08-31 03:47
Like wurst can detect the .(command) and then run a command why cant it detect the $w and then change all a's to z's and b's to y's? it should be possible. and i see where once it gets known it would be obvious who's hacking but that's only if its jumbled up. if it is still using the alphabet people could just say that its a different language

**Comment by mcccs** [comment] 2015-08-31 08:50
#89 
![](https://cloud.githubusercontent.com/assets/11584045/9006833/5819b95e-3794-11e5-8af0-b02894caded7.png)

**Comment by pokeball99** [comment] 2015-08-31 11:42
Oh,right,this is a dupe of that in the sense...

**Closed** 2015-09-04 16:39 UTC
