### ISSUE TITLE
Turn on/off

### ISSUE THREAD

**Issue by GhostGuy283** [Wurst-Imperium/Wurst-Client#716] opened 2015-05-06 07:55 UTC
make a feature that you can disable and enable wurst! or maybe a hide button that you can make screenshots and nobody sees that you are hacking!

**Comment by GummiBoat** [comment] 2015-05-06 07:58
Press F1 to hide your GUI completely.

Next time please search for your matter instead of opening a new issue.
![Image](http://puu.sh/hC1Fc/1af12ad39d.png)

Duplicate of #19.

**Closed** 2015-05-06 13:50 UTC
Labels: duplicate
