### ISSUE TITLE
Cracked Server Tester

### ISSUE THREAD

**Issue by Krypt2** [Wurst-Imperium/Wurst-Client#2112] opened 2015-09-04 23:30 UTC
A function in the Server finder, which tests if the server is a cracked server or not. Is that possible?

**Comment by pokeball99** [comment] 2015-09-04 23:54
Dupe of ( insert @gummiboat here )

**Comment by awakened-game** [comment] 2015-09-05 06:40
Simple soloution:
Don't be lazy and just connect as a cracked user, if wurst says no, its not cracked, done.

**Closed** 2015-11-28 19:43 UTC
