### ISSUE TITLE
AutoPrisonMiner

### ISSUE THREAD

**Issue by TabooBaboo** [Wurst-Imperium/Wurst-Client#557] opened 2015-04-19 18:49 UTC
Hey! I wondered IF you could do a auto miner and seller for prison servers. If you have played prison you know that mining is boring as shit. 

It could: Mine, mine itself up and go to the sell sign and click on it so it sells all, and then repeat. IF you added it, it would need a  auto-detect for full inventory, so it doesn't keep ming :P

**Comment by pokeball99** [comment] 2015-04-19 18:58
Kinda dupe of https://github.com/Wurst-Imperium/Wurst-Client/issues/456

**Comment by OMGchangeMYusername** [comment] 2015-04-19 20:23
i don't think it'd be that simple..
it'll just waste your time if you work on it.
**not saying it's not useful!** but it's not worth the effort..
and just as the dupe-obsessed pokeball said, the excavator is enough.
**no offence was intended :)**

**Comment by pokeball99** [comment] 2015-04-19 21:07
dupe-obsessed?

**Comment by arnont33** [comment] 2015-05-22 03:20
this is good idea :D for who play prison servers !

**Comment by OMGchangeMYusername** [comment] 2015-05-27 01:55
Wouldn't you close this? it's strange coz you rejected it without closing it O.o

**Closed** 2015-05-27 07:13 UTC
Labels: enhancement, mod, rejected
