### ISSUE TITLE
Enabling MassTPA crashes the client.

### ISSUE THREAD

**Issue by Ericyeah** [Wurst-Imperium/Wurst-Client#53] opened 2015-02-21 00:34 UTC

**Comment by Alexander01998** [comment] 2015-02-21 10:35
No, it doesn't.

Seriously dude, enough the low quality Issues. If you don't put any effort into it, I won't put effort into it either. I'll just close it as `invalid`.

**Closed by Alexander01998** 2015-02-21 10:35 UTC

**Comment by Ericyeah** [comment] 2015-02-23 18:03
Not long ago you closed an issue I had because I had a mac, if that's not lacking quality in a project's maintenance I don't know what is.

**Comment by Alexander01998** [comment] 2015-02-23 18:43
> Not long ago you closed an issue I had because I had a mac, if that's not lacking quality in a project's maintenance I don't know what is.

I closed #49 because it required more information and could not be reproduced. If you get offended by that, that's your problem.

**Comment by Ericyeah** [comment] 2015-02-23 18:59
I got "offended" by your attribution of my issue to the fact I was using a mac in a snide way.

We're using the word offended in the lightest way possible mind you.

Plus, you totally just ignored my feature request, that bow thing would be pretty cool.

**Comment by Alexander01998** [comment] 2015-02-23 19:44
> I got "offended" by your attribution of my issue to the fact I was using a mac in a snide way.
> 
> We're using the word offended in the lightest way possible mind you.

Not only I, but the whole Wurst-Imperium is strongly against crApple and none of us is afraid of saying anything that could offend crApple fans.

That said, I talked to Grünwald32, the leader of the Wurst-Imperium anti-crApple movement. This is what he said:

>So Alex, I have no idea what to say about that guy. I mean, if he's dumb enough (to use crApple), if he's dumb enough... then he doesn't deserve an answer.
>I'm speachless. Someone must have pooped into this guy's nose.
>Damn, that these people still exist.

.
> Plus, you totally just ignored my feature request, that bow thing would be pretty cool.

I decide which suggestions to accept and which ones to deny. It's not my duty to accept any suggestions, regardless of how much the person who suggested it likes it.

**Comment by Ericyeah** [comment] 2015-02-24 15:41
@Alexander01998 Are you a moron? Because I think you're a moron. Please point me in the direction of the website offering free windows computers with decent specs, unless such a site exists, I'm making the best of what I got, you've yet to even identify any issues with Apple laptops, aside from the fact they cost way too much, it seems you're just calling them shitty without providing any information as to why you dislike them, which is inherently obnoxious.

I never identified myself as a fan of apple computers, but you simply assume because I own one I'm a fan, it sounds like you're the 'dumb' one. Grow up.
