### ISSUE TITLE
PNT (player name typer)

### ISSUE THREAD

**Issue by 8bitPotato** [Wurst-Imperium/Wurst-Client#882] opened 2015-06-06 05:28 UTC
this is a thing where in the chat of servers you can type something in and the name says the player name you want it to be for example: I'm bobby122 but I want to type in the chat as PurpleBanana123
so I type the username down and what I type shows

PurpleBanana123: Hi 

instead of

bobby122: Hi

**Comment by OMGchangeMYusername** [comment] 2015-06-06 08:36
Duplicate #748. I think they're the same :P

**Comment by Alexander01998** [comment] 2015-06-06 12:18
If this is meant to be client-side, it's a duplicate of #748. If it's meant to be server-side, it's not possible.

**Closed by Alexander01998** 2015-06-06 12:18 UTC
