### ISSUE TITLE
Forge Modloader Possible?

### ISSUE THREAD

**Issue by ravenje** [Wurst-Imperium/Wurst-Client#637] opened 2015-04-26 20:19 UTC
Is there a way to forge 1.8 to use in wust?
Because mods such as minimap?
Maybe someone can help me ...

**Comment by GummiBoat** [comment] 2015-04-26 22:01
Already rejected. Duplicate of #464

**Closed** 2015-04-27 13:51 UTC

**Comment by TekkitCommando** [comment] 2015-04-27 14:47
That would cause unneeded lag and you wouldn't be able to use any mods but minimal making it not worth it

**Comment by TekkitCommando** [comment] 2015-04-27 14:48
Minimap*
