### ISSUE TITLE
Auto soul plis 

### ISSUE THREAD

**Issue by hackrex** [Wurst-Imperium/Wurst-Client#1702] opened 2015-08-08 22:23 UTC
auto soup !!!!

**Comment by pokeball99** [comment] 2015-08-08 22:25
Dupe

**Comment by hackrex** [comment] 2015-08-08 22:29
Autosoup to complete the hack

**Comment by EnderGamer21** [comment] 2015-08-08 23:33
UAto Soup is like fast eat or auto eat And is implmented kinda

**Comment by OMGchangeMYusername** [comment] 2015-08-09 02:34
Duplicate #83.
Please search for old issues next time.

**Comment by mcccs** [comment] 2015-08-09 08:05
THis is not a duplicate of #83
It was in old.wurst-client.tk in old times.

**Comment by OMGchangeMYusername** [comment] 2015-08-09 08:08
... ?

**Comment by mcccs** [comment] 2015-08-09 08:38
It was in WuCl's site in 6 months early

**Comment by OMGchangeMYusername** [comment] 2015-08-09 09:03
wow you appear to be a little dumb.. unless you're joking.

**Closed** 2015-08-09 11:02 UTC
Labels: duplicate
