### ISSUE TITLE
Idea - Simulate launch position of arrows: SimulateArrow

### ISSUE THREAD

**Issue by Lakitu** [Wurst-Imperium/Wurst-Client#310] opened 2015-03-23 18:05 UTC
Hi,

I've an idea for a new mod. It's named "SimulateArrow" or "Projectiles". It will simulate where the arrow will launch, if you fire it. I don't know how it works, but there are other clients with this mod, for example Huzuni. They've called it "Projectiles", it generates a line to a circle what is positioned on the place where the arrow will launch. Sorry for bad English, I hope that you understand it. ;)

Lakitu

**Comment by OMGchangeMYusername** [comment] 2015-03-23 19:51
This is a duplicate of **Trajectories** #168 
there's no difference except for the name.

You might be new but Please review the [Guidelines for contributing] (https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) to this repository,Mainly the issues section.

**Closed** 2015-03-23 20:18 UTC
