### ISSUE TITLE
Increased item range?

### ISSUE THREAD

**Issue by superluig164** [Wurst-Imperium/Wurst-Client#1695] opened 2015-08-08 02:45 UTC
Add a hack that causes your item pickup radius to be larger?

**Comment by OMGchangeMYusername** [comment] 2015-08-08 02:48
Duplicate #144 
Search old issues next time ;)

**Comment by superluig164** [comment] 2015-08-08 22:30
I did, and nothing came up...

**Comment by OMGchangeMYusername** [comment] 2015-08-09 02:44
Don't search "Increased item range?".. 
Search for words that are related to your suggestion, read [this article] (https://help.github.com/articles/searching-issues/) about how to easily search what you want.
You'll most likely find issue number 849, because of the words there, but then you'll see that it's a duplicate of 144 and that way avoid duplicating ;)

**Closed** 2015-08-09 10:40 UTC
Labels: duplicate
