### ISSUE TITLE
New Wurst Logo

### ISSUE THREAD

**Issue by pasi123567** [Wurst-Imperium/Wurst-Client#1383] opened 2015-07-25 10:05 UTC
I know someone else made something like this already, but im not bad in Photoshop so i tried 1 myself.

Here are my 2 versions:
1: http://i.imgur.com/6VebKkT.png
2: http://i.imgur.com/G6J7vg2.png

**Comment by mcccs** [comment] 2015-07-25 11:45
You should make 
505x128
882x223
705.600x621(loading)
these images

**Comment by pasi123567** [comment] 2015-07-25 12:06
What do you mean with 705.600x621(loading)  exactly?

**Comment by mcccs** [comment] 2015-07-25 14:40
the loading screen

**Comment by pasi123567** [comment] 2015-07-25 15:25
But what you mean with 700.600x621? I dont understand that

**Comment by TekkitCommando** [comment] 2015-07-25 16:03
meant to put a x i think

**Comment by OMGchangeMYusername** [comment] 2015-07-25 16:21
>I seem to be the only one who has heard the saying: “Keep your logo and your style as long as you can, that way people will remember your brand!”. With all those clients constantly changing their looks nowadays, you can’t really tell the difference anymore. The moment you memorized a logo or a color scheme, it changes completely. Keeping the style of Wurst has been a huge advantage recently, enough to turn it into the 4th most popular client on WiZARDHAX.com (it was #5 before). -Alexander01998

So yeah.

**Comment by OMGchangeMYusername** [comment] 2015-07-25 16:22
https://www.wurst-client.tk/news/2015-07-01-Wurst-2.0-status/ if you're wondering where i quoted that.

**Comment by pasi123567** [comment] 2015-07-25 17:48
Yeah but its still not that much of a change, well see if alexander says something about this.

**Comment by OMGchangeMYusername** [comment] 2015-07-25 18:02
I totally agree to a new look, however WITHOUT changing the logo. the main menu should look better, but the logo must stay as it is. I loved the look Orcunegecar made when he was announcing Wurst project for dream browser.

**Comment by pasi123567** [comment] 2015-07-25 18:11
The logo looks so "old" for me and because of that i made this logo.
(I like those modern-metro styles really much)

**Comment by OMGchangeMYusername** [comment] 2015-07-25 18:20
I totally agree to a new front GUI, where buttons are in somewhere else and have different look, however without changing the logo. something like the picture in #196, where the logo is the same but the GUI looks a little different.

**Comment by pasi123567** [comment] 2015-07-25 18:26
Thats everyones own view.
I would like both.
Still not as in the picture. (A bit more detailed)
I could try making an menu design, but i cant code.

**Comment by OMGchangeMYusername** [comment] 2015-07-25 18:37
> Still not as in the picture. (A bit more detailed)

Agreed.
But "new logo" is a duplicate of #938.

**Comment by pasi123567** [comment] 2015-07-25 18:41
As i said i know that someone made an logo already but mine looks different. so i thought ill open a new "issue" for this one.

**Comment by pasi123567** [comment] 2015-07-26 14:52
http://i.imgur.com/j4l5vix.png
I made this so far.
Important! I can just make the design not the coding.
Now the questions. What should i change?
Are the colors good?
Ill make a version with the old Wurst logo too.

**Comment by pokeball99** [comment] 2015-07-26 14:56
ehh.....idk how to explain it,but it looks....not wurst-ish,can someone agree/explain?

**Comment by pasi123567** [comment] 2015-07-26 14:58
Yeah it look strange for me too

**Comment by pokeball99** [comment] 2015-07-26 15:00
and yet,your the one to design it......

**Comment by pasi123567** [comment] 2015-07-26 15:02
yep i know

**Comment by pasi123567** [comment] 2015-07-26 15:03
Maybe you could tell me how it should look?

**Comment by bob80333** [comment] 2015-07-26 15:09
It's missing options and quit game buttons, and survival should be single player.

**Comment by pasi123567** [comment] 2015-07-26 15:14
Thats not the point. Its not done

**Comment by pokeball99** [comment] 2015-07-26 15:19
well maybe as the panoramic(idk if i spelled that write,the background in the main menu) could be a greifed server/build

**Comment by pasi123567** [comment] 2015-07-26 15:23
Thanks ill test it

**Comment by pasi123567** [comment] 2015-07-26 15:40
hmm....
http://i.imgur.com/IOildK1.png

**Comment by OMGchangeMYusername** [comment] 2015-07-26 16:09
that looks like a game on flash games website..
If i were to suggest, make it a very simple dark design, it's not good if it's so colorful.

**Comment by pasi123567** [comment] 2015-07-26 16:24
So you say no colored background? How did you find the 1st one?

**Comment by OMGchangeMYusername** [comment] 2015-07-26 16:34
it's ok to me any damn way, but that design is lame tbh..

**Comment by pasi123567** [comment] 2015-07-26 16:35
I know it looks like sh*t

**Comment by pasi123567** [comment] 2015-07-26 16:38
Ill try an new one ok?

**Comment by OMGchangeMYusername** [comment] 2015-07-26 16:45
Google "metal backgrounds" for inspirations.

Also i really doubt he'll accept it, try the original logo.

**Comment by pasi123567** [comment] 2015-07-26 17:11
http://i.imgur.com/mz1DiTd.png

I can change the logo at the end

**Comment by pokeball99** [comment] 2015-07-26 17:29
how about something like this:
puu.sh/2DlpF

**Comment by pasi123567** [comment] 2015-07-26 17:30
damnit

**Comment by OMGchangeMYusername** [comment] 2015-07-26 17:33
> how about something like this:
puu.sh/2DlpF

Nice design, keep it up!

**Comment by GummiBoat** [comment] 2015-07-26 17:34
@pasi123567 Please, don't make the buttons look like that, that's horrible... something like 
![this](http://www.uiparade.com/wp-content/uploads/2012/06/clean-modern-ui-web-button.jpg)
 or 
![that](http://designscrazed.org/wp-content/uploads/2014/06/radio-buttons.jpg)
should be definitely enough.

it's definitely okay to pick a background, try something like a pack of TNT, like in the main image of the [Wurst website](https://www.wurst-client.tk/).

**Comment by OMGchangeMYusername** [comment] 2015-07-26 17:39
> like in the main image of the Wurst website.

woah that'll look bad. unless you change it a lil..

**Comment by pasi123567** [comment] 2015-07-26 18:54
I think ill give up... NO ILL NEVER GIVE UP
http://i.imgur.com/MwQ7AR2.png

**Comment by OMGchangeMYusername** [comment] 2015-07-26 19:38
Who's ill?

**Comment by pasi123567** [comment] 2015-07-26 19:59
I'll* :D (I will)

**Comment by pasi123567** [comment] 2015-07-26 20:53
http://i.imgur.com/0f1fh2d.jpg

**Comment by bob80333** [comment] 2015-07-26 20:58
Looks nice  :thumbsup:

**Comment by pasi123567** [comment] 2015-07-26 21:00
Thanks :3

**Comment by pasi123567** [comment] 2015-07-26 21:32
And here the same with the original wurst logo:
http://i.imgur.com/MBFID2K.jpg

**Comment by OMGchangeMYusername** [comment] 2015-07-27 07:03
Looks good :+1:

**Comment by pasi123567** [comment] 2015-07-27 14:12
Maybe still some suggestions?

**Comment by labcraft59** [comment] 2015-07-27 14:30
I like the Wurst logo the way it is, sorry.

**Comment by pasi123567** [comment] 2015-07-27 16:16
http://i.imgur.com/XBkm8ni.png

**Comment by pasi123567** [comment] 2015-07-27 16:55
I think i dont have hobbies
http://i.imgur.com/gRmXwvj.png

**Comment by pasi123567** [comment] 2015-07-27 16:56
Im doing this just for fun i dont even think this will be accepted xD

**Comment by bob80333** [comment] 2015-07-27 17:02
What is that? The alt-manager?

**Comment by pasi123567** [comment] 2015-07-27 17:02
Yeah xD

**Comment by GlitchHead** [comment] 2015-07-28 03:06
@pokeball99 ive lasted so long without getting rick rolled :c but thanks for the link!

**Comment by mcccs** [comment] 2015-07-29 07:01
@pasi123567 849x799

**Comment by mcccs** [comment] 2015-07-29 07:05
@pasi123567 you should make seperate images for buttons, so ill suggest you make loading screen with 849x799. Loading screen needs no coding

**Comment by pasi123567** [comment] 2015-07-29 17:53
Sure but before that i wait for alexander to see what he thinks.
(Best english ever)

**Closed** 2015-07-31 21:19 UTC
Labels: enhancement, rejected

**Comment by pasi123567** [comment] 2015-08-01 11:01
yay :D 
xD
