### ISSUE TITLE
Xray Possibility to remove annoying things like Signs

### ISSUE THREAD

**Issue by pasi123567** [Wurst-Imperium/Wurst-Client#1370] opened 2015-07-24 17:23 UTC
Is this Possible? I never saw that on any hacked client in my live

**Comment by WurstContributor** [comment] 2015-07-24 20:46
Its a bug and a duplicate of an issue i dont remember

**Comment by GummiBoat** [comment] 2015-07-24 21:04
# *Duplicate: #211*

![](https://camo.githubusercontent.com/fde0e4b68d36e2d72331263e4c421c56965a71df/687474703a2f2f692e696d6775722e636f6d2f714a4a514930582e706e67)

**Comment by pasi123567** [comment] 2015-07-25 09:32
Thanks i didnt saw it.

**Closed** 2015-07-25 09:32 UTC
