### ISSUE TITLE
.enchant command for survival

### ISSUE THREAD

**Issue by TrollFace101Omega** [Wurst-Imperium/Wurst-Client#667] opened 2015-05-01 11:56 UTC
Why can you only use .enchant in creative? Why not survival? Plus, you should add the ability to put single enchants, like .enchant protection_3, .enchant fireaspect_1, etc.

**Comment by OMGchangeMYusername** [comment] 2015-05-01 13:23
because it's only possible in creative :angry: 
also,that's a duplicate of #603

**Closed** 2015-05-01 17:31 UTC
Labels: invalid
