### ISSUE TITLE
Quakeaura

### ISSUE THREAD

**Issue by Grievus** [Wurst-Imperium/Wurst-Client#2198] opened 2015-09-11 13:54 UTC
This hack will atomatticly aim at a player from a long distance so you can shoot him directly in dah face in quakecraft.

**Comment by GamingGamer12** [comment] 2015-09-11 21:58
bowaimbot is already implmented

**Comment by PgBiel** [comment] 2015-09-12 00:46
He means Quakecraft. In quakecraft it uses Hoes as the weapon.

**Comment by FlareHAX0R** [comment] 2015-09-13 17:52
Will work on sometime this week. Probably today/tomorrow

**Comment by PixelMaster3D** [comment] 2015-09-14 13:34
Duplicate of #55

**Closed** 2015-09-18 18:54 UTC
Labels: duplicate
