### ISSUE TITLE
FarmBot

### ISSUE THREAD

**Issue by 49ers2001** [Wurst-Imperium/Wurst-Client#700] opened 2015-05-04 15:03 UTC
Hey guys

My Suggestion is a farm bot where you type the id/ids of the blocks you want to farm and a bot farms it for you so you can just relax. This Mod can be made by a combinations of Autotool/autowalk/autospring/automine/search and many more. it would be great if this was possible because I could come in very handy

**Comment by pokeball99** [comment] 2015-05-04 15:33
dupe of https://github.com/Wurst-Imperium/Wurst-Client/issues/384

**Closed** 2015-05-04 20:12 UTC
