### ISSUE TITLE
Add GUI For .give and .potion

### ISSUE THREAD

**Issue by Al00X** [Wurst-Imperium/Wurst-Client#2118] opened 2015-09-05 07:59 UTC
Hi , Can you add GUI for .give and .potion ?
this can be  very good and :star: special :star: 
this feature will make .give and .potion very faster use and easier ... 

thankYou

**Comment by awakened-game** [comment] 2015-09-05 08:54
i guess you could clone the creative inventory for the .give GUI, but i cant imagine what a .potion GUI would do or have.

**Comment by Al00X** [comment] 2015-09-05 09:02
a GUI like this ... 
![gui](https://cloud.githubusercontent.com/assets/12069672/9698579/7aa54574-53d2-11e5-98c2-e67a9ffe82ee.png)

Very Ugly Paint lol :D , but this is just Suggestion ;)
if alexander add it wurst will be great

**Comment by PixelMaster3D** [comment] 2015-09-05 20:05
An easy way to novices.

**Comment by Al00X** [comment] 2015-09-06 07:33
:| , i know it's take some time to create this , i just give this suggestion for better wurst !

**Comment by pokeball99** [comment] 2015-09-06 15:00
Dupe of....one second let me get it

**Closed** 2015-11-28 19:43 UTC
Labels: decision: pending
