### ISSUE TITLE
Add Optifine

### ISSUE THREAD

**Issue by Mr-Nubs** [Wurst-Imperium/Wurst-Client#1908] opened 2015-08-19 15:25 UTC
I would like optifine as a feature so I can run smoothly and enjoy the client even better!

**Comment by pokeball99** [comment] 2015-08-19 15:33
dupe of #2
https://cloud.githubusercontent.com/assets/10976441/9021444/990e8990-3842-11e5-809e-a06b796a4328.png

**Comment by EnderGamer21** [comment] 2015-08-19 17:33
dupe of many other things

**Closed** 2015-08-19 19:28 UTC
Labels: duplicate
