### ISSUE TITLE
Scrape Feature!

### ISSUE THREAD

**Issue by SuperSushil** [Wurst-Imperium/Wurst-Client#1949] opened 2015-08-22 00:50 UTC
So I got this feature , its a scraping feature where you scrape usernames from a server not like the whole server but the Players in the Mini game or lobby 
to use this scrape feature is .scrape and it saves to the wurst folder 
PS I am new to this GitHub so sorry if I did something wrong also I took inspiration from Weepcraft

**Comment by linuxcodefire** [comment] 2015-08-22 00:52
Well I believe this was asked before but good luck.

**Comment by SuperSushil** [comment] 2015-08-22 00:55
KK thanks

**Comment by pokeball99** [comment] 2015-08-22 03:12
Dupe of..... um, @Gummiboat a little help?

**Comment by JackFishbaugh** [comment] 2015-08-22 04:52
lol @pokeball99 .

When you need help finding,
A previous issue

Who you gonna call?

@Gummiboat!!!

**Comment by mcccs** [comment] 2015-08-22 08:30
#278 ![](https://cloud.githubusercontent.com/assets/11584045/9006833/5819b95e-3794-11e5-8af0-b02894caded7.png)

**Comment by linuxcodefire** [comment] 2015-08-22 13:24
-.-

**Closed** 2015-09-04 18:01 UTC
Labels: duplicate

**Comment by PixelMaster3D** [comment] 2015-09-05 19:51
Weepcraft has it. There's your confirmation. For issue #278
