### ISSUE TITLE
I can't get out of error report

### ISSUE THREAD

**Issue by scriptinator** [Wurst-Imperium/Wurst-Client#995] opened 2015-06-19 20:21 UTC
I was doing .drop on a server and it gave me a bug when I clicked report bug it did not exit out of bug screen and instead said in chat (My chat) that something went wrong. I could not go back to game.
The error was processing events
All I could do was copy the report
> This is an auto-generated error report for the [Wurst Client](https://www.wurst-client.tk).

# Description
�desc

# Stacktrace
```
�trace
```

# System details
- OS: �os
- Java version: �java
- Wurst version: �wurst
- Timestamp: �time

**Comment by Alexander01998** [comment] 2015-06-19 20:43
This is the template that is used to generate error reports. It should not be possible without serious modifications that Wurst generates an error report without replacing the placeholders (`§trace`, `§time`, etc.) with actual data.

So I assume that you are using a modified version, which means that this bug was caused by your modifications and can only be fixed by you. This assumption is also based on some of your previous issues (#962, #652, #645, #629), which were also caused by modifications you made.

However, if you are able to prove me wrong, feel free to leave a comment.

**Comment by scriptinator** [comment] 2015-06-20 16:43
I have been unable to modify Wurst as I am still dealing with Eclipse being weird. I am using the official versions of Wurst 1.15.

**Comment by Alexander01998** [comment] 2015-06-20 17:12
Well then, a more detailed description of the bug is required in order to fix it. Please include the following information:
- Steps to reproduce the error
- Operating system
- Java version(s)
- Non-minified stack trace (can usually be found in the "Output" tab of the Minecraft launcher)
- Default charset

**Closed** 2015-07-07 13:06 UTC
Labels: bug, more info required
