### ISSUE TITLE
Wurst Client Disable

### ISSUE THREAD

**Issue by MangoAssassin** [Wurst-Imperium/Wurst-Client#723] opened 2015-05-07 00:49 UTC
So yeah, ive seen all of the other topics about having a button to disable the client, but I never read a full response. So is there one or no?

**Comment by GummiBoat** [comment] 2015-05-07 07:43
No.

Duplicate of #19 .

**Comment by MangoAssassin** [comment] 2015-05-07 21:05
Aw. Why not?

**Closed** 2015-05-07 21:06 UTC

**Comment by OMGchangeMYusername** [comment] 2015-05-08 10:33
well this would be useful but Alexander won't accept it anyway so yeah..
