### ISSUE TITLE
Can you make Wurst mod loader??

### ISSUE THREAD

**Issue by billyoz** [Wurst-Imperium/Wurst-Client#648] opened 2015-04-28 07:15 UTC
Wurst Hacked Client + Modloader??
Thats Amazing

**Comment by GummiBoat** [comment] 2015-04-28 07:27
This was already rejected several times. Next time search the Issues for your matter and read the guidelines to create an issue. Duplicate of #637

**Closed** 2015-04-28 12:05 UTC
Labels: duplicate
