### ISSUE TITLE
afking section

### ISSUE THREAD

**Issue by pshaper** [Wurst-Imperium/Wurst-Client#1083] opened 2015-06-28 00:35 UTC
i think there should be an afk part where you can do auto jump, auto afk, afk machine build. and then on some servers they have mcmmo and i think there should be AFK Weapon, where when you right click it you can choose if you want to afk with an axe or a sword. the afk weapon would do this: Whenever your current selected weapon breaks, another weapon that is the same kind as the one that just broke will be replaced into the hand slot. this is also for swords. If you know what auto armor is, its the same but when the chosen weapon in your hand slot breaks, if you have more of that weapon it takes another of that weapon and puts it into the hand slot. PLEASE IF YOU ADD THIS AFK WEAPON, PLEASE ADD AXES ALOT OF PEOPLE USE AXES

**Comment by OMGchangeMYusername** [comment] 2015-06-28 01:16
I'm ok with a section for "Auto" mods because they are a lot,but AFKweapon is some kinda duplicate of #718.

**Comment by Huanjohn** [comment] 2015-06-28 03:05
@OMGchangeMYusername To me, they seem to be different concepts; one preventing you from breaking a tool, and the other replacing the tool you broke with another one from your inventory.

**Comment by GummiBoat** [comment] 2015-06-28 09:30
Okay, I understand, that you don't want to actively level your Skills and/or want do to better things, while your McMMO Stats go crazy. But, there are a few little details, that you're missing. First, in order to activate the specific tool, you would need to check, is there a possibility to even activate it? Then, what is the most efficient way to use it? (Axes on big trees, etc.) After that, it's necessary to calculate the best possible route (yes, .goto does that, but you don't need to go to the point where it is, but -1 block, and if there is a block too, +1 block, etc.), and then it constantly needs to check the chat for the message, that your stuff is ready again.

You see, it is a lot of effort, to automate McMMO, because it's not supposed to be leveled AFK.

**Comment by OMGchangeMYusername** [comment] 2015-06-28 14:46
k i just wanna know,why would someone need a sword/axe when *he is AFK*?
maybe Fightbot is what you're talking about,idk but that didn't sound afk at all,or is it farming/grinding?

**Closed** 2015-06-28 16:54 UTC
Labels: enhancement, rejected
