### ISSUE TITLE
Aimbot

### ISSUE THREAD

**Issue by eveythingistaken** [Wurst-Imperium/Wurst-Client#654] opened 2015-04-29 16:58 UTC
Yes, I know this is a duplicate. I just want you to see it because I have to tell you something. I understand how you think it wouldn't be useful, but it is. The reason I want it at the moment is because I have a magma slime grinder on this one server but I still have to kill the slimes. They don't die automatically. Something is wrong with multiaura, and it only attacks them sometimes. It's like when they get too close or something it stops attacking (I have to be close to them to pick up the money they drop). If alot of people want it, why can't you add it just take make people happy? I would turn on triggerbot and aimtbot so I can just always hit them. Please Alexander.

Come to think of it, you could also just make us be able to activate multiaura and triggerbot at the same time. That'd be useful.

**Comment by TekkitCommando** [comment] 2015-04-29 18:05
Begging

**Comment by eveythingistaken** [comment] 2015-04-29 18:53
@TekkitCommando who, me?

**Comment by GlitchHead** [comment] 2015-04-29 19:18
yes this is a duplicate... so you *comment* on the issue this is a duplicate of not create a new issue.

**Closed** 2015-04-29 19:29 UTC
