### ISSUE TITLE
SlaveMode

### ISSUE THREAD

**Issue by beppe9000** [Wurst-Imperium/Wurst-Client#2171] opened 2015-09-08 15:50 UTC
*Would not it be cool to control Wurst from any programming language?*
## Yes! ##

Thanks to [IPC (Interprocess Communication)](http://austingwalters.com/introduction-to-ipc-interprocess-communication#main) this can be achieved.

![ipc image](http://austingwalters.com/wp-content/uploads/2014/05/Screen-Shot-2014-05-07-at-3.20.41-PM2.png "IPC Example")

I was thinking about some named pipes as an initial approach to this thing:
* a pipe for console commands,
* one to mirror chat (with timestamps) and/or client log,
* one to output client data such as player positions, blocks etc.,
* and finally, one (altough a socket may better serve this dual-way duty) that exposes all sort of client functions (like player movement, inventory etc.) thrugh object serialization (json\xml\anything).

Looks like a trivial task to do in java altough some native differentiation is needed for cross-platform support.

I think this feature (if realized) will lead the way to an interesting ecosystem of supercontroller-mods and give a new level of scripting to Wurst (cmd scripts or bash script have native access to pipes).

Also people wouldn't need Java in order to extend Wurst with things like auto-bidders, chat bots and anything.

**Comment by nerdtron123** [comment] 2015-10-04 20:11
-1

**Comment by beppe9000** [comment] 2015-10-06 06:15
Can you care to explain why you disagree with this integration mod proposal?

**Comment by nerdtron123** [comment] 2015-10-06 15:58
Because, it would cause many bugs and there is another dupe of this btw, If you want custom code in the client learn java and git and then fork it and apply patches etc, Also it would take lots of work. And also it would take off the multiplatform support on Wurst.

**Comment by mcccs** [comment] 2015-10-07 05:02
And a lot of users dont know coding

**Comment by beppe9000** [comment] 2015-10-11 00:26
- **Bugs**: I think you are referring to the third communication channel: that is a bonus, if chat integration is not enough we could devise and use such a method for data interchange. However, as long as we stick to chat integration and command issuing, everything is managed internally by Wurst, piping the commands directly to the chat parser, and implementing needed functions as commands there should be no bugs as it is anothere interface to the same underlying implementation.

 - **I had no luck searching.** Could you please reference the duplicate issue? 

 - **Custom code**: what i proposed here is not a single-task mod but a cross-language platform for others to build server-specific mod implementations without cluttering the repository with unrelated code. <br>Ever heard of browser extensions? One does not simply learn C/C++ to add a damn button on a toolbar.

 - **Multiplatform support** will be unmodified, as later research shows how it is possible to achieve interprocess communication trough local TCP\UDP sockets.<br>As an inherent  bonus you could also use this system remotely by changing the socket bindings/address.

- **Most of the people here** are "*dumb end users*"... Well, they wouldn't use it. But others will. And will have a platform to build more creative hacks/mods/bots by integrating wurst with external programs. <br>
(An example: Have you ever used the Pause key on your keyboard?)

**Closed** 2015-11-28 19:40 UTC
