### ISSUE TITLE
PotionESP

### ISSUE THREAD

**Issue by haykam** [Wurst-Imperium/Wurst-Client#1360] opened 2015-07-24 03:04 UTC
Allows you to highlight entities with 2 things: either a box like other ESPs showing the potion color (like dark red for harming) or a box half the size of the potion effects you see in the inventory, that shows the icon and name. If it's possible you can also add time left.

Edit: Another feature: to change options, you'd do ".potionesp box" for the other-ESP like boxes and ".potionesp info" for the icon, name, and time left-style.

**Comment by OMGchangeMYusername** [comment] 2015-07-24 03:59
I would say this is dupe of #159 since they're almost identical (both show "too much data on the screen"). But i guess this is a little different since it's for other players..

About the idea, i like it. But not exactly as ESP, I'd prefer a small text under/above nametags e.g "resistance II (3:10)".

**Comment by haykam** [comment] 2015-07-24 04:03
Ok. I'll change that as another option.

**Comment by haykam** [comment] 2015-08-02 23:44
Wait, this was the original so let's keep this one open.

**Closed** 2015-08-04 16:23 UTC
Labels: duplicate
