### ISSUE TITLE
Crash on AFK

### ISSUE THREAD

**Issue by PopTrop972** [Wurst-Imperium/Wurst-Client#841] opened 2015-05-30 19:58 UTC
After a few hours, I got back on my pc to see an almost completely dark screen and at the top was "Minecraft 1.8 (Not Responding)." I was going to put the crash report in here but accidentally deleted it. 

Help I'm on a windows laptop and the Wurst client is version 1.14.1

**Comment by Nitrogen-Dioxide** [comment] 2015-05-30 20:21
Probably it is the spontaneous crash...

**Comment by Alexander01998** [comment] 2015-05-31 05:13
Probably a duplicate of #642.

**Closed by Alexander01998** 2015-05-31 05:13 UTC
