### ISSUE TITLE
Force op

### ISSUE THREAD

**Issue by NudelFresse** [Wurst-Imperium/Wurst-Client#826] opened 2015-05-25 13:16 UTC
i dont know if it is a bug, but when i want to join a server with a cracked acc there is written down : "Your IP doesnt match with your old one" could you fix it or did i made something wrong ?

**Comment by Senkaaaa** [comment] 2015-05-25 13:32
That is not a bug, it is a server plugin and cannot be fixed within the client.

**Closed** 2015-05-25 13:34 UTC
Labels: bug, disconfirmed

**Comment by NudelFresse** [comment] 2015-05-25 13:56
do you know whats that plugin called ? because i found a server and i also have the acc of the owner in my altlist

**Comment by OMGchangeMYusername** [comment] 2015-05-25 16:48
> when i want to join a server with a cracked acc there is written down : "Your IP doesnt match with your old one"

You used a cracked alt on an online server? that won't work anyway.
if you couldn't join any server,idk it might be a bug. 
But if it was only that specific server,it might be [this plugin] (http://www.curse.com/bukkit-plugins/minecraft/ip-check-jnk)...

**Comment by GummiBoat** [comment] 2015-05-25 17:34
@OMGchangeMYusername I think it's actually [this one](http://dev.bukkit.org/bukkit-plugins/accountguard/) .

And I don't think it'll be helpful for you @NudelFresse, because I don't think you will be able to change your IP Address to the Server Owners IP.

**Comment by OMGchangeMYusername** [comment] 2015-05-25 18:26
He asked for it anyway~

**Comment by scriptinator** [comment] 2015-05-26 21:31
I have heard something about changing ur ip with iptables

**Comment by GummiBoat** [comment] 2015-05-26 22:51
@scriptinator Yes, it's possible. But! First, "IPTables" (or NAT) is for Linux. Second, it's not as easy as it sounds. And on top of that, he still needs to gain the IP associated with the Owners Account.
