### ISSUE TITLE
A radar

### ISSUE THREAD

**Issue by MrPIEEEEEEEEEEEEEEEEEEEW** [Wurst-Imperium/Wurst-Client#1043] opened 2015-06-25 00:52 UTC
You should add in a radar so we can see a list of people's names that are near us

**Comment by OMGchangeMYusername** [comment] 2015-06-25 01:08
Please review the [guidelines for contributing] (https://github.com/Wurst-Imperium/Wurst-Client/blob/master/CONTRIBUTING.md) to this repository.
This is a duplicate of #303.

**Closed** 2015-06-25 15:19 UTC
Labels: duplicate
