### ISSUE TITLE
VideoSafe

### ISSUE THREAD

**Issue by haykam** [Wurst-Imperium/Wurst-Client#722] opened 2015-05-07 00:27 UTC
Basically a toggle to show/hide the Wurst logo on the main menu, hide the alt manager thingy, and all other signs of hacking so it is safe to publish on YouTube or Twitch without revealing you are hacking. This should also be kept toggled when off, like a setting in the Minecraft menu does. This would help very much.

**Comment by TekkitCommando** [comment] 2015-05-07 02:07
This has been denied and duplicated so many times

**Comment by GummiBoat** [comment] 2015-05-07 07:48
Your Question has been asked in the issue 19, 26, 74, 233, 630, 643, 708 ... and i probably forgot some.

Duplicate of #19.

Next time please search your matter before opening a new request,
![Image](https://camo.githubusercontent.com/9b7cbf889d96d03740a87192086701362872e8fd/687474703a2f2f7075752e73682f68433146632f316166313261643339642e706e67)

**Closed** 2015-05-07 21:06 UTC
Labels: duplicate
